apiVersion: v1
kind: ConfigMap
metadata:
  name: cllone-config
  namespace: cllone
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_ENGINE: postgresql
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  # Substitua SEU_IP_PUBLICO pelo IP público da instância EC2 (porta 30100)
  CORS_ALLOWED_ORIGINS: "http://SEU_IP_PUBLICO:30100"
  CSRF_TRUSTED_ORIGINS: "http://SEU_IP_PUBLICO:30100"
