apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cllone
  namespace: argocd
spec:
  project: default
  source:
    # Troque pelo URL do seu repositório GitOps
    repoURL: https://github.com/henrique-furtado47/cllone-gitops.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cllone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
